/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// QueryMetadata The query metadata containing pagination metadata.
type QueryMetadata struct {
	Pagination *QueryMetadataPagination `json:"pagination,omitempty"`
}

// NewQueryMetadata instantiates a new QueryMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryMetadata() *QueryMetadata {
	this := QueryMetadata{}
	return &this
}

// NewQueryMetadataWithDefaults instantiates a new QueryMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryMetadataWithDefaults() *QueryMetadata {
	this := QueryMetadata{}
	return &this
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *QueryMetadata) GetPagination() QueryMetadataPagination {
	if o == nil || o.Pagination == nil {
		var ret QueryMetadataPagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryMetadata) GetPaginationOk() (*QueryMetadataPagination, bool) {
	if o == nil || o.Pagination == nil {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *QueryMetadata) HasPagination() bool {
	if o != nil && o.Pagination != nil {
		return true
	}

	return false
}

// SetPagination gets a reference to the given QueryMetadataPagination and assigns it to the Pagination field.
func (o *QueryMetadata) SetPagination(v QueryMetadataPagination) {
	o.Pagination = &v
}

func (o QueryMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pagination != nil {
		toSerialize["pagination"] = o.Pagination
	}
	return json.Marshal(toSerialize)
}

type NullableQueryMetadata struct {
	value *QueryMetadata
	isSet bool
}

func (v NullableQueryMetadata) Get() *QueryMetadata {
	return v.value
}

func (v *NullableQueryMetadata) Set(val *QueryMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryMetadata(val *QueryMetadata) *NullableQueryMetadata {
	return &NullableQueryMetadata{value: val, isSet: true}
}

func (v NullableQueryMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
