/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// IncidentTimelineCellStatusChangeContent A Status Change cell content schema.
type IncidentTimelineCellStatusChangeContent struct {
	// The markdown content of the status change for the cell.
	Content string `json:"content"`
	// A string representing the status change type.
	StatusType string `json:"status_type"`
}

// NewIncidentTimelineCellStatusChangeContent instantiates a new IncidentTimelineCellStatusChangeContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentTimelineCellStatusChangeContent(content string, statusType string) *IncidentTimelineCellStatusChangeContent {
	this := IncidentTimelineCellStatusChangeContent{}
	this.Content = content
	this.StatusType = statusType
	return &this
}

// NewIncidentTimelineCellStatusChangeContentWithDefaults instantiates a new IncidentTimelineCellStatusChangeContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentTimelineCellStatusChangeContentWithDefaults() *IncidentTimelineCellStatusChangeContent {
	this := IncidentTimelineCellStatusChangeContent{}
	return &this
}

// GetContent returns the Content field value
func (o *IncidentTimelineCellStatusChangeContent) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *IncidentTimelineCellStatusChangeContent) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *IncidentTimelineCellStatusChangeContent) SetContent(v string) {
	o.Content = v
}

// GetStatusType returns the StatusType field value
func (o *IncidentTimelineCellStatusChangeContent) GetStatusType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StatusType
}

// GetStatusTypeOk returns a tuple with the StatusType field value
// and a boolean to check if the value has been set.
func (o *IncidentTimelineCellStatusChangeContent) GetStatusTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusType, true
}

// SetStatusType sets field value
func (o *IncidentTimelineCellStatusChangeContent) SetStatusType(v string) {
	o.StatusType = v
}

func (o IncidentTimelineCellStatusChangeContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["content"] = o.Content
	}
	if true {
		toSerialize["status_type"] = o.StatusType
	}
	return json.Marshal(toSerialize)
}

// AsIncidentTimelineCellCommonContentOneOf wraps this instance of IncidentTimelineCellStatusChangeContent in IncidentTimelineCellCommonContentOneOf
func (s *IncidentTimelineCellStatusChangeContent) AsIncidentTimelineCellCommonContentOneOf() IncidentTimelineCellCommonContentOneOf {
	return IncidentTimelineCellCommonContentOneOf{IncidentTimelineCellCommonContentOneOfInterface: s}
}

type NullableIncidentTimelineCellStatusChangeContent struct {
	value *IncidentTimelineCellStatusChangeContent
	isSet bool
}

func (v NullableIncidentTimelineCellStatusChangeContent) Get() *IncidentTimelineCellStatusChangeContent {
	return v.value
}

func (v *NullableIncidentTimelineCellStatusChangeContent) Set(val *IncidentTimelineCellStatusChangeContent) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentTimelineCellStatusChangeContent) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentTimelineCellStatusChangeContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentTimelineCellStatusChangeContent(val *IncidentTimelineCellStatusChangeContent) *NullableIncidentTimelineCellStatusChangeContent {
	return &NullableIncidentTimelineCellStatusChangeContent{value: val, isSet: true}
}

func (v NullableIncidentTimelineCellStatusChangeContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentTimelineCellStatusChangeContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
