/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
	"time"
)

// IncidentConfigFieldAttributes The JSON API Schema attributes.
type IncidentConfigFieldAttributes struct {
	// Timestamp of when the field was created.
	Created *time.Time `json:"created,omitempty"`
	// The default Incident Config Choice/value for the provided field.
	DefaultChoiceId *string `json:"default_choice_id,omitempty"`
	// Timestamp of when the field was modified.
	Modified *time.Time `json:"modified,omitempty"`
	// Name of the field.
	Name    *string                   `json:"name,omitempty"`
	TableId *IncidentConfigFieldTable `json:"table_id,omitempty"`
	Type    *IncidentConfigFieldType  `json:"type,omitempty"`
}

// NewIncidentConfigFieldAttributes instantiates a new IncidentConfigFieldAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentConfigFieldAttributes() *IncidentConfigFieldAttributes {
	this := IncidentConfigFieldAttributes{}
	return &this
}

// NewIncidentConfigFieldAttributesWithDefaults instantiates a new IncidentConfigFieldAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentConfigFieldAttributesWithDefaults() *IncidentConfigFieldAttributes {
	this := IncidentConfigFieldAttributes{}
	return &this
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *IncidentConfigFieldAttributes) GetCreated() time.Time {
	if o == nil || o.Created == nil {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigFieldAttributes) GetCreatedOk() (*time.Time, bool) {
	if o == nil || o.Created == nil {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *IncidentConfigFieldAttributes) HasCreated() bool {
	if o != nil && o.Created != nil {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *IncidentConfigFieldAttributes) SetCreated(v time.Time) {
	o.Created = &v
}

// GetDefaultChoiceId returns the DefaultChoiceId field value if set, zero value otherwise.
func (o *IncidentConfigFieldAttributes) GetDefaultChoiceId() string {
	if o == nil || o.DefaultChoiceId == nil {
		var ret string
		return ret
	}
	return *o.DefaultChoiceId
}

// GetDefaultChoiceIdOk returns a tuple with the DefaultChoiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigFieldAttributes) GetDefaultChoiceIdOk() (*string, bool) {
	if o == nil || o.DefaultChoiceId == nil {
		return nil, false
	}
	return o.DefaultChoiceId, true
}

// HasDefaultChoiceId returns a boolean if a field has been set.
func (o *IncidentConfigFieldAttributes) HasDefaultChoiceId() bool {
	if o != nil && o.DefaultChoiceId != nil {
		return true
	}

	return false
}

// SetDefaultChoiceId gets a reference to the given string and assigns it to the DefaultChoiceId field.
func (o *IncidentConfigFieldAttributes) SetDefaultChoiceId(v string) {
	o.DefaultChoiceId = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *IncidentConfigFieldAttributes) GetModified() time.Time {
	if o == nil || o.Modified == nil {
		var ret time.Time
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigFieldAttributes) GetModifiedOk() (*time.Time, bool) {
	if o == nil || o.Modified == nil {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *IncidentConfigFieldAttributes) HasModified() bool {
	if o != nil && o.Modified != nil {
		return true
	}

	return false
}

// SetModified gets a reference to the given time.Time and assigns it to the Modified field.
func (o *IncidentConfigFieldAttributes) SetModified(v time.Time) {
	o.Modified = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IncidentConfigFieldAttributes) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigFieldAttributes) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IncidentConfigFieldAttributes) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IncidentConfigFieldAttributes) SetName(v string) {
	o.Name = &v
}

// GetTableId returns the TableId field value if set, zero value otherwise.
func (o *IncidentConfigFieldAttributes) GetTableId() IncidentConfigFieldTable {
	if o == nil || o.TableId == nil {
		var ret IncidentConfigFieldTable
		return ret
	}
	return *o.TableId
}

// GetTableIdOk returns a tuple with the TableId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigFieldAttributes) GetTableIdOk() (*IncidentConfigFieldTable, bool) {
	if o == nil || o.TableId == nil {
		return nil, false
	}
	return o.TableId, true
}

// HasTableId returns a boolean if a field has been set.
func (o *IncidentConfigFieldAttributes) HasTableId() bool {
	if o != nil && o.TableId != nil {
		return true
	}

	return false
}

// SetTableId gets a reference to the given IncidentConfigFieldTable and assigns it to the TableId field.
func (o *IncidentConfigFieldAttributes) SetTableId(v IncidentConfigFieldTable) {
	o.TableId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IncidentConfigFieldAttributes) GetType() IncidentConfigFieldType {
	if o == nil || o.Type == nil {
		var ret IncidentConfigFieldType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigFieldAttributes) GetTypeOk() (*IncidentConfigFieldType, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IncidentConfigFieldAttributes) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given IncidentConfigFieldType and assigns it to the Type field.
func (o *IncidentConfigFieldAttributes) SetType(v IncidentConfigFieldType) {
	o.Type = &v
}

func (o IncidentConfigFieldAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Created != nil {
		toSerialize["created"] = o.Created
	}
	if o.DefaultChoiceId != nil {
		toSerialize["default_choice_id"] = o.DefaultChoiceId
	}
	if o.Modified != nil {
		toSerialize["modified"] = o.Modified
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.TableId != nil {
		toSerialize["table_id"] = o.TableId
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableIncidentConfigFieldAttributes struct {
	value *IncidentConfigFieldAttributes
	isSet bool
}

func (v NullableIncidentConfigFieldAttributes) Get() *IncidentConfigFieldAttributes {
	return v.value
}

func (v *NullableIncidentConfigFieldAttributes) Set(val *IncidentConfigFieldAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentConfigFieldAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentConfigFieldAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentConfigFieldAttributes(val *IncidentConfigFieldAttributes) *NullableIncidentConfigFieldAttributes {
	return &NullableIncidentConfigFieldAttributes{value: val, isSet: true}
}

func (v NullableIncidentConfigFieldAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentConfigFieldAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
