/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
	"time"
)

// IncidentCreateWithInitialDataAttributes The Incident attributes.
type IncidentCreateWithInitialDataAttributes struct {
	// Timestamp of when an incident was created.
	Created *time.Time `json:"created,omitempty"`
	// Timestamp of when cusomters/users were no longer impacted by the incident.
	CustomerImpactEnd NullableTime `json:"customer_impact_end,omitempty"`
	// The scope at which customers were impacted.
	CustomerImpactScope *string `json:"customer_impact_scope,omitempty"`
	// Timestamp of when cusomters/users were impacted by the incident.
	CustomerImpactStart NullableTime `json:"customer_impact_start,omitempty"`
	// True if customers/users were impacted by the incident.
	CustomerImpacted *bool `json:"customer_impacted,omitempty"`
	// Timestamp of when an incident was detected.
	Detected NullableTime `json:"detected,omitempty"`
	// Length of the incident representing the delta of customer_impact_end-customer_impact_start.
	Duration *int64 `json:"duration,omitempty"`
	// An array of initial timeline cell definitions to include.
	InitialCells *[]IncidentTimelineCellCommon `json:"initial_cells,omitempty"`
	// An array of initial choices when creating an incident.
	InitialUserDefinedFieldChoices *[]IncidentInitialUserDefinedFieldChoices `json:"initial_user_defined_field_choices,omitempty"`
	// Timestamp of when an incident was last modified.
	Modified *time.Time `json:"modified,omitempty"`
	// Unique auto incrementing id for each created incident specific to the organization.
	PublicId *int64 `json:"public_id,omitempty"`
	// Timestamp of when an incident was resolved.
	Resolved NullableTime `json:"resolved,omitempty"`
	// The current state if an incident.
	State *string `json:"state,omitempty"`
	// The amount of time in seconds to detect the incident.
	TimeToDetect *int64 `json:"time_to_detect,omitempty"`
	// The amount of time in seconds to detect the incidents occurence. Represents the delta of detected - created.
	TimeToInternalResponse *int64 `json:"time_to_internal_response,omitempty"`
	// The amount of time in seconds to resolve customer impact after detecting the issue. Represents the delta of customer_impact_end - detected.
	TimeToRepair *int64 `json:"time_to_repair,omitempty"`
	// The title of the incident.
	Title *string `json:"title,omitempty"`
}

// NewIncidentCreateWithInitialDataAttributes instantiates a new IncidentCreateWithInitialDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentCreateWithInitialDataAttributes() *IncidentCreateWithInitialDataAttributes {
	this := IncidentCreateWithInitialDataAttributes{}
	return &this
}

// NewIncidentCreateWithInitialDataAttributesWithDefaults instantiates a new IncidentCreateWithInitialDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentCreateWithInitialDataAttributesWithDefaults() *IncidentCreateWithInitialDataAttributes {
	this := IncidentCreateWithInitialDataAttributes{}
	return &this
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *IncidentCreateWithInitialDataAttributes) GetCreated() time.Time {
	if o == nil || o.Created == nil {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentCreateWithInitialDataAttributes) GetCreatedOk() (*time.Time, bool) {
	if o == nil || o.Created == nil {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasCreated() bool {
	if o != nil && o.Created != nil {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *IncidentCreateWithInitialDataAttributes) SetCreated(v time.Time) {
	o.Created = &v
}

// GetCustomerImpactEnd returns the CustomerImpactEnd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IncidentCreateWithInitialDataAttributes) GetCustomerImpactEnd() time.Time {
	if o == nil || o.CustomerImpactEnd.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.CustomerImpactEnd.Get()
}

// GetCustomerImpactEndOk returns a tuple with the CustomerImpactEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IncidentCreateWithInitialDataAttributes) GetCustomerImpactEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerImpactEnd.Get(), o.CustomerImpactEnd.IsSet()
}

// HasCustomerImpactEnd returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasCustomerImpactEnd() bool {
	if o != nil && o.CustomerImpactEnd.IsSet() {
		return true
	}

	return false
}

// SetCustomerImpactEnd gets a reference to the given NullableTime and assigns it to the CustomerImpactEnd field.
func (o *IncidentCreateWithInitialDataAttributes) SetCustomerImpactEnd(v time.Time) {
	o.CustomerImpactEnd.Set(&v)
}

// SetCustomerImpactEndNil sets the value for CustomerImpactEnd to be an explicit nil
func (o *IncidentCreateWithInitialDataAttributes) SetCustomerImpactEndNil() {
	o.CustomerImpactEnd.Set(nil)
}

// UnsetCustomerImpactEnd ensures that no value is present for CustomerImpactEnd, not even an explicit nil
func (o *IncidentCreateWithInitialDataAttributes) UnsetCustomerImpactEnd() {
	o.CustomerImpactEnd.Unset()
}

// GetCustomerImpactScope returns the CustomerImpactScope field value if set, zero value otherwise.
func (o *IncidentCreateWithInitialDataAttributes) GetCustomerImpactScope() string {
	if o == nil || o.CustomerImpactScope == nil {
		var ret string
		return ret
	}
	return *o.CustomerImpactScope
}

// GetCustomerImpactScopeOk returns a tuple with the CustomerImpactScope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentCreateWithInitialDataAttributes) GetCustomerImpactScopeOk() (*string, bool) {
	if o == nil || o.CustomerImpactScope == nil {
		return nil, false
	}
	return o.CustomerImpactScope, true
}

// HasCustomerImpactScope returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasCustomerImpactScope() bool {
	if o != nil && o.CustomerImpactScope != nil {
		return true
	}

	return false
}

// SetCustomerImpactScope gets a reference to the given string and assigns it to the CustomerImpactScope field.
func (o *IncidentCreateWithInitialDataAttributes) SetCustomerImpactScope(v string) {
	o.CustomerImpactScope = &v
}

// GetCustomerImpactStart returns the CustomerImpactStart field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IncidentCreateWithInitialDataAttributes) GetCustomerImpactStart() time.Time {
	if o == nil || o.CustomerImpactStart.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.CustomerImpactStart.Get()
}

// GetCustomerImpactStartOk returns a tuple with the CustomerImpactStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IncidentCreateWithInitialDataAttributes) GetCustomerImpactStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerImpactStart.Get(), o.CustomerImpactStart.IsSet()
}

// HasCustomerImpactStart returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasCustomerImpactStart() bool {
	if o != nil && o.CustomerImpactStart.IsSet() {
		return true
	}

	return false
}

// SetCustomerImpactStart gets a reference to the given NullableTime and assigns it to the CustomerImpactStart field.
func (o *IncidentCreateWithInitialDataAttributes) SetCustomerImpactStart(v time.Time) {
	o.CustomerImpactStart.Set(&v)
}

// SetCustomerImpactStartNil sets the value for CustomerImpactStart to be an explicit nil
func (o *IncidentCreateWithInitialDataAttributes) SetCustomerImpactStartNil() {
	o.CustomerImpactStart.Set(nil)
}

// UnsetCustomerImpactStart ensures that no value is present for CustomerImpactStart, not even an explicit nil
func (o *IncidentCreateWithInitialDataAttributes) UnsetCustomerImpactStart() {
	o.CustomerImpactStart.Unset()
}

// GetCustomerImpacted returns the CustomerImpacted field value if set, zero value otherwise.
func (o *IncidentCreateWithInitialDataAttributes) GetCustomerImpacted() bool {
	if o == nil || o.CustomerImpacted == nil {
		var ret bool
		return ret
	}
	return *o.CustomerImpacted
}

// GetCustomerImpactedOk returns a tuple with the CustomerImpacted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentCreateWithInitialDataAttributes) GetCustomerImpactedOk() (*bool, bool) {
	if o == nil || o.CustomerImpacted == nil {
		return nil, false
	}
	return o.CustomerImpacted, true
}

// HasCustomerImpacted returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasCustomerImpacted() bool {
	if o != nil && o.CustomerImpacted != nil {
		return true
	}

	return false
}

// SetCustomerImpacted gets a reference to the given bool and assigns it to the CustomerImpacted field.
func (o *IncidentCreateWithInitialDataAttributes) SetCustomerImpacted(v bool) {
	o.CustomerImpacted = &v
}

// GetDetected returns the Detected field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IncidentCreateWithInitialDataAttributes) GetDetected() time.Time {
	if o == nil || o.Detected.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.Detected.Get()
}

// GetDetectedOk returns a tuple with the Detected field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IncidentCreateWithInitialDataAttributes) GetDetectedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Detected.Get(), o.Detected.IsSet()
}

// HasDetected returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasDetected() bool {
	if o != nil && o.Detected.IsSet() {
		return true
	}

	return false
}

// SetDetected gets a reference to the given NullableTime and assigns it to the Detected field.
func (o *IncidentCreateWithInitialDataAttributes) SetDetected(v time.Time) {
	o.Detected.Set(&v)
}

// SetDetectedNil sets the value for Detected to be an explicit nil
func (o *IncidentCreateWithInitialDataAttributes) SetDetectedNil() {
	o.Detected.Set(nil)
}

// UnsetDetected ensures that no value is present for Detected, not even an explicit nil
func (o *IncidentCreateWithInitialDataAttributes) UnsetDetected() {
	o.Detected.Unset()
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *IncidentCreateWithInitialDataAttributes) GetDuration() int64 {
	if o == nil || o.Duration == nil {
		var ret int64
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentCreateWithInitialDataAttributes) GetDurationOk() (*int64, bool) {
	if o == nil || o.Duration == nil {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasDuration() bool {
	if o != nil && o.Duration != nil {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int64 and assigns it to the Duration field.
func (o *IncidentCreateWithInitialDataAttributes) SetDuration(v int64) {
	o.Duration = &v
}

// GetInitialCells returns the InitialCells field value if set, zero value otherwise.
func (o *IncidentCreateWithInitialDataAttributes) GetInitialCells() []IncidentTimelineCellCommon {
	if o == nil || o.InitialCells == nil {
		var ret []IncidentTimelineCellCommon
		return ret
	}
	return *o.InitialCells
}

// GetInitialCellsOk returns a tuple with the InitialCells field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentCreateWithInitialDataAttributes) GetInitialCellsOk() (*[]IncidentTimelineCellCommon, bool) {
	if o == nil || o.InitialCells == nil {
		return nil, false
	}
	return o.InitialCells, true
}

// HasInitialCells returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasInitialCells() bool {
	if o != nil && o.InitialCells != nil {
		return true
	}

	return false
}

// SetInitialCells gets a reference to the given []IncidentTimelineCellCommon and assigns it to the InitialCells field.
func (o *IncidentCreateWithInitialDataAttributes) SetInitialCells(v []IncidentTimelineCellCommon) {
	o.InitialCells = &v
}

// GetInitialUserDefinedFieldChoices returns the InitialUserDefinedFieldChoices field value if set, zero value otherwise.
func (o *IncidentCreateWithInitialDataAttributes) GetInitialUserDefinedFieldChoices() []IncidentInitialUserDefinedFieldChoices {
	if o == nil || o.InitialUserDefinedFieldChoices == nil {
		var ret []IncidentInitialUserDefinedFieldChoices
		return ret
	}
	return *o.InitialUserDefinedFieldChoices
}

// GetInitialUserDefinedFieldChoicesOk returns a tuple with the InitialUserDefinedFieldChoices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentCreateWithInitialDataAttributes) GetInitialUserDefinedFieldChoicesOk() (*[]IncidentInitialUserDefinedFieldChoices, bool) {
	if o == nil || o.InitialUserDefinedFieldChoices == nil {
		return nil, false
	}
	return o.InitialUserDefinedFieldChoices, true
}

// HasInitialUserDefinedFieldChoices returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasInitialUserDefinedFieldChoices() bool {
	if o != nil && o.InitialUserDefinedFieldChoices != nil {
		return true
	}

	return false
}

// SetInitialUserDefinedFieldChoices gets a reference to the given []IncidentInitialUserDefinedFieldChoices and assigns it to the InitialUserDefinedFieldChoices field.
func (o *IncidentCreateWithInitialDataAttributes) SetInitialUserDefinedFieldChoices(v []IncidentInitialUserDefinedFieldChoices) {
	o.InitialUserDefinedFieldChoices = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *IncidentCreateWithInitialDataAttributes) GetModified() time.Time {
	if o == nil || o.Modified == nil {
		var ret time.Time
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentCreateWithInitialDataAttributes) GetModifiedOk() (*time.Time, bool) {
	if o == nil || o.Modified == nil {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasModified() bool {
	if o != nil && o.Modified != nil {
		return true
	}

	return false
}

// SetModified gets a reference to the given time.Time and assigns it to the Modified field.
func (o *IncidentCreateWithInitialDataAttributes) SetModified(v time.Time) {
	o.Modified = &v
}

// GetPublicId returns the PublicId field value if set, zero value otherwise.
func (o *IncidentCreateWithInitialDataAttributes) GetPublicId() int64 {
	if o == nil || o.PublicId == nil {
		var ret int64
		return ret
	}
	return *o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentCreateWithInitialDataAttributes) GetPublicIdOk() (*int64, bool) {
	if o == nil || o.PublicId == nil {
		return nil, false
	}
	return o.PublicId, true
}

// HasPublicId returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasPublicId() bool {
	if o != nil && o.PublicId != nil {
		return true
	}

	return false
}

// SetPublicId gets a reference to the given int64 and assigns it to the PublicId field.
func (o *IncidentCreateWithInitialDataAttributes) SetPublicId(v int64) {
	o.PublicId = &v
}

// GetResolved returns the Resolved field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IncidentCreateWithInitialDataAttributes) GetResolved() time.Time {
	if o == nil || o.Resolved.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.Resolved.Get()
}

// GetResolvedOk returns a tuple with the Resolved field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IncidentCreateWithInitialDataAttributes) GetResolvedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Resolved.Get(), o.Resolved.IsSet()
}

// HasResolved returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasResolved() bool {
	if o != nil && o.Resolved.IsSet() {
		return true
	}

	return false
}

// SetResolved gets a reference to the given NullableTime and assigns it to the Resolved field.
func (o *IncidentCreateWithInitialDataAttributes) SetResolved(v time.Time) {
	o.Resolved.Set(&v)
}

// SetResolvedNil sets the value for Resolved to be an explicit nil
func (o *IncidentCreateWithInitialDataAttributes) SetResolvedNil() {
	o.Resolved.Set(nil)
}

// UnsetResolved ensures that no value is present for Resolved, not even an explicit nil
func (o *IncidentCreateWithInitialDataAttributes) UnsetResolved() {
	o.Resolved.Unset()
}

// GetState returns the State field value if set, zero value otherwise.
func (o *IncidentCreateWithInitialDataAttributes) GetState() string {
	if o == nil || o.State == nil {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentCreateWithInitialDataAttributes) GetStateOk() (*string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *IncidentCreateWithInitialDataAttributes) SetState(v string) {
	o.State = &v
}

// GetTimeToDetect returns the TimeToDetect field value if set, zero value otherwise.
func (o *IncidentCreateWithInitialDataAttributes) GetTimeToDetect() int64 {
	if o == nil || o.TimeToDetect == nil {
		var ret int64
		return ret
	}
	return *o.TimeToDetect
}

// GetTimeToDetectOk returns a tuple with the TimeToDetect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentCreateWithInitialDataAttributes) GetTimeToDetectOk() (*int64, bool) {
	if o == nil || o.TimeToDetect == nil {
		return nil, false
	}
	return o.TimeToDetect, true
}

// HasTimeToDetect returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasTimeToDetect() bool {
	if o != nil && o.TimeToDetect != nil {
		return true
	}

	return false
}

// SetTimeToDetect gets a reference to the given int64 and assigns it to the TimeToDetect field.
func (o *IncidentCreateWithInitialDataAttributes) SetTimeToDetect(v int64) {
	o.TimeToDetect = &v
}

// GetTimeToInternalResponse returns the TimeToInternalResponse field value if set, zero value otherwise.
func (o *IncidentCreateWithInitialDataAttributes) GetTimeToInternalResponse() int64 {
	if o == nil || o.TimeToInternalResponse == nil {
		var ret int64
		return ret
	}
	return *o.TimeToInternalResponse
}

// GetTimeToInternalResponseOk returns a tuple with the TimeToInternalResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentCreateWithInitialDataAttributes) GetTimeToInternalResponseOk() (*int64, bool) {
	if o == nil || o.TimeToInternalResponse == nil {
		return nil, false
	}
	return o.TimeToInternalResponse, true
}

// HasTimeToInternalResponse returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasTimeToInternalResponse() bool {
	if o != nil && o.TimeToInternalResponse != nil {
		return true
	}

	return false
}

// SetTimeToInternalResponse gets a reference to the given int64 and assigns it to the TimeToInternalResponse field.
func (o *IncidentCreateWithInitialDataAttributes) SetTimeToInternalResponse(v int64) {
	o.TimeToInternalResponse = &v
}

// GetTimeToRepair returns the TimeToRepair field value if set, zero value otherwise.
func (o *IncidentCreateWithInitialDataAttributes) GetTimeToRepair() int64 {
	if o == nil || o.TimeToRepair == nil {
		var ret int64
		return ret
	}
	return *o.TimeToRepair
}

// GetTimeToRepairOk returns a tuple with the TimeToRepair field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentCreateWithInitialDataAttributes) GetTimeToRepairOk() (*int64, bool) {
	if o == nil || o.TimeToRepair == nil {
		return nil, false
	}
	return o.TimeToRepair, true
}

// HasTimeToRepair returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasTimeToRepair() bool {
	if o != nil && o.TimeToRepair != nil {
		return true
	}

	return false
}

// SetTimeToRepair gets a reference to the given int64 and assigns it to the TimeToRepair field.
func (o *IncidentCreateWithInitialDataAttributes) SetTimeToRepair(v int64) {
	o.TimeToRepair = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *IncidentCreateWithInitialDataAttributes) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentCreateWithInitialDataAttributes) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialDataAttributes) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *IncidentCreateWithInitialDataAttributes) SetTitle(v string) {
	o.Title = &v
}

func (o IncidentCreateWithInitialDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Created != nil {
		toSerialize["created"] = o.Created
	}
	if o.CustomerImpactEnd.IsSet() {
		toSerialize["customer_impact_end"] = o.CustomerImpactEnd.Get()
	}
	if o.CustomerImpactScope != nil {
		toSerialize["customer_impact_scope"] = o.CustomerImpactScope
	}
	if o.CustomerImpactStart.IsSet() {
		toSerialize["customer_impact_start"] = o.CustomerImpactStart.Get()
	}
	if o.CustomerImpacted != nil {
		toSerialize["customer_impacted"] = o.CustomerImpacted
	}
	if o.Detected.IsSet() {
		toSerialize["detected"] = o.Detected.Get()
	}
	if o.Duration != nil {
		toSerialize["duration"] = o.Duration
	}
	if o.InitialCells != nil {
		toSerialize["initial_cells"] = o.InitialCells
	}
	if o.InitialUserDefinedFieldChoices != nil {
		toSerialize["initial_user_defined_field_choices"] = o.InitialUserDefinedFieldChoices
	}
	if o.Modified != nil {
		toSerialize["modified"] = o.Modified
	}
	if o.PublicId != nil {
		toSerialize["public_id"] = o.PublicId
	}
	if o.Resolved.IsSet() {
		toSerialize["resolved"] = o.Resolved.Get()
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.TimeToDetect != nil {
		toSerialize["time_to_detect"] = o.TimeToDetect
	}
	if o.TimeToInternalResponse != nil {
		toSerialize["time_to_internal_response"] = o.TimeToInternalResponse
	}
	if o.TimeToRepair != nil {
		toSerialize["time_to_repair"] = o.TimeToRepair
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	return json.Marshal(toSerialize)
}

type NullableIncidentCreateWithInitialDataAttributes struct {
	value *IncidentCreateWithInitialDataAttributes
	isSet bool
}

func (v NullableIncidentCreateWithInitialDataAttributes) Get() *IncidentCreateWithInitialDataAttributes {
	return v.value
}

func (v *NullableIncidentCreateWithInitialDataAttributes) Set(val *IncidentCreateWithInitialDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentCreateWithInitialDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentCreateWithInitialDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentCreateWithInitialDataAttributes(val *IncidentCreateWithInitialDataAttributes) *NullableIncidentCreateWithInitialDataAttributes {
	return &NullableIncidentCreateWithInitialDataAttributes{value: val, isSet: true}
}

func (v NullableIncidentCreateWithInitialDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentCreateWithInitialDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
