/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// IncidentCreateWithInitialData For creating incidents you can also pass initial data for signals and choice selections
type IncidentCreateWithInitialData struct {
	Attributes *IncidentCreateWithInitialDataAttributes `json:"attributes,omitempty"`
}

// NewIncidentCreateWithInitialData instantiates a new IncidentCreateWithInitialData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentCreateWithInitialData() *IncidentCreateWithInitialData {
	this := IncidentCreateWithInitialData{}
	return &this
}

// NewIncidentCreateWithInitialDataWithDefaults instantiates a new IncidentCreateWithInitialData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentCreateWithInitialDataWithDefaults() *IncidentCreateWithInitialData {
	this := IncidentCreateWithInitialData{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *IncidentCreateWithInitialData) GetAttributes() IncidentCreateWithInitialDataAttributes {
	if o == nil || o.Attributes == nil {
		var ret IncidentCreateWithInitialDataAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentCreateWithInitialData) GetAttributesOk() (*IncidentCreateWithInitialDataAttributes, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *IncidentCreateWithInitialData) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given IncidentCreateWithInitialDataAttributes and assigns it to the Attributes field.
func (o *IncidentCreateWithInitialData) SetAttributes(v IncidentCreateWithInitialDataAttributes) {
	o.Attributes = &v
}

func (o IncidentCreateWithInitialData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableIncidentCreateWithInitialData struct {
	value *IncidentCreateWithInitialData
	isSet bool
}

func (v NullableIncidentCreateWithInitialData) Get() *IncidentCreateWithInitialData {
	return v.value
}

func (v *NullableIncidentCreateWithInitialData) Set(val *IncidentCreateWithInitialData) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentCreateWithInitialData) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentCreateWithInitialData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentCreateWithInitialData(val *IncidentCreateWithInitialData) *NullableIncidentCreateWithInitialData {
	return &NullableIncidentCreateWithInitialData{value: val, isSet: true}
}

func (v NullableIncidentCreateWithInitialData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentCreateWithInitialData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
