/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// UserJSONAPIIDData The User data.
type UserJSONAPIIDData struct {
	// A unique identifier that represents the user.
	Id *string `json:"id,omitempty"`
	// JSONAPI Model Type
	Type *string `json:"type,omitempty"`
}

// NewUserJSONAPIIDData instantiates a new UserJSONAPIIDData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserJSONAPIIDData() *UserJSONAPIIDData {
	this := UserJSONAPIIDData{}
	var type_ string = "users"
	this.Type = &type_
	return &this
}

// NewUserJSONAPIIDDataWithDefaults instantiates a new UserJSONAPIIDData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserJSONAPIIDDataWithDefaults() *UserJSONAPIIDData {
	this := UserJSONAPIIDData{}
	var type_ string = "users"
	this.Type = &type_
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UserJSONAPIIDData) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserJSONAPIIDData) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UserJSONAPIIDData) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UserJSONAPIIDData) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *UserJSONAPIIDData) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserJSONAPIIDData) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *UserJSONAPIIDData) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *UserJSONAPIIDData) SetType(v string) {
	o.Type = &v
}

func (o UserJSONAPIIDData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableUserJSONAPIIDData struct {
	value *UserJSONAPIIDData
	isSet bool
}

func (v NullableUserJSONAPIIDData) Get() *UserJSONAPIIDData {
	return v.value
}

func (v *NullableUserJSONAPIIDData) Set(val *UserJSONAPIIDData) {
	v.value = val
	v.isSet = true
}

func (v NullableUserJSONAPIIDData) IsSet() bool {
	return v.isSet
}

func (v *NullableUserJSONAPIIDData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserJSONAPIIDData(val *UserJSONAPIIDData) *NullableUserJSONAPIIDData {
	return &NullableUserJSONAPIIDData{value: val, isSet: true}
}

func (v NullableUserJSONAPIIDData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserJSONAPIIDData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
