/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
	"time"
)

// IncidentConfigFieldChoiceAttributes The JSON API Schema attributes.
type IncidentConfigFieldChoiceAttributes struct {
	// Timestamp of when the field was created
	Created *time.Time `json:"created,omitempty"`
	// Timestamp of when the field was modified
	Modified *time.Time `json:"modified,omitempty"`
	// Name of the field
	Name *string `json:"name,omitempty"`
	// The ID of the associated field
	UserDefinedFieldId *string `json:"user_defined_field_id,omitempty"`
	// value of the field
	Value *string `json:"value,omitempty"`
}

// NewIncidentConfigFieldChoiceAttributes instantiates a new IncidentConfigFieldChoiceAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentConfigFieldChoiceAttributes() *IncidentConfigFieldChoiceAttributes {
	this := IncidentConfigFieldChoiceAttributes{}
	return &this
}

// NewIncidentConfigFieldChoiceAttributesWithDefaults instantiates a new IncidentConfigFieldChoiceAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentConfigFieldChoiceAttributesWithDefaults() *IncidentConfigFieldChoiceAttributes {
	this := IncidentConfigFieldChoiceAttributes{}
	return &this
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *IncidentConfigFieldChoiceAttributes) GetCreated() time.Time {
	if o == nil || o.Created == nil {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigFieldChoiceAttributes) GetCreatedOk() (*time.Time, bool) {
	if o == nil || o.Created == nil {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *IncidentConfigFieldChoiceAttributes) HasCreated() bool {
	if o != nil && o.Created != nil {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *IncidentConfigFieldChoiceAttributes) SetCreated(v time.Time) {
	o.Created = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *IncidentConfigFieldChoiceAttributes) GetModified() time.Time {
	if o == nil || o.Modified == nil {
		var ret time.Time
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigFieldChoiceAttributes) GetModifiedOk() (*time.Time, bool) {
	if o == nil || o.Modified == nil {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *IncidentConfigFieldChoiceAttributes) HasModified() bool {
	if o != nil && o.Modified != nil {
		return true
	}

	return false
}

// SetModified gets a reference to the given time.Time and assigns it to the Modified field.
func (o *IncidentConfigFieldChoiceAttributes) SetModified(v time.Time) {
	o.Modified = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IncidentConfigFieldChoiceAttributes) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigFieldChoiceAttributes) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IncidentConfigFieldChoiceAttributes) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IncidentConfigFieldChoiceAttributes) SetName(v string) {
	o.Name = &v
}

// GetUserDefinedFieldId returns the UserDefinedFieldId field value if set, zero value otherwise.
func (o *IncidentConfigFieldChoiceAttributes) GetUserDefinedFieldId() string {
	if o == nil || o.UserDefinedFieldId == nil {
		var ret string
		return ret
	}
	return *o.UserDefinedFieldId
}

// GetUserDefinedFieldIdOk returns a tuple with the UserDefinedFieldId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigFieldChoiceAttributes) GetUserDefinedFieldIdOk() (*string, bool) {
	if o == nil || o.UserDefinedFieldId == nil {
		return nil, false
	}
	return o.UserDefinedFieldId, true
}

// HasUserDefinedFieldId returns a boolean if a field has been set.
func (o *IncidentConfigFieldChoiceAttributes) HasUserDefinedFieldId() bool {
	if o != nil && o.UserDefinedFieldId != nil {
		return true
	}

	return false
}

// SetUserDefinedFieldId gets a reference to the given string and assigns it to the UserDefinedFieldId field.
func (o *IncidentConfigFieldChoiceAttributes) SetUserDefinedFieldId(v string) {
	o.UserDefinedFieldId = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *IncidentConfigFieldChoiceAttributes) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigFieldChoiceAttributes) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *IncidentConfigFieldChoiceAttributes) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *IncidentConfigFieldChoiceAttributes) SetValue(v string) {
	o.Value = &v
}

func (o IncidentConfigFieldChoiceAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Created != nil {
		toSerialize["created"] = o.Created
	}
	if o.Modified != nil {
		toSerialize["modified"] = o.Modified
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.UserDefinedFieldId != nil {
		toSerialize["user_defined_field_id"] = o.UserDefinedFieldId
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableIncidentConfigFieldChoiceAttributes struct {
	value *IncidentConfigFieldChoiceAttributes
	isSet bool
}

func (v NullableIncidentConfigFieldChoiceAttributes) Get() *IncidentConfigFieldChoiceAttributes {
	return v.value
}

func (v *NullableIncidentConfigFieldChoiceAttributes) Set(val *IncidentConfigFieldChoiceAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentConfigFieldChoiceAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentConfigFieldChoiceAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentConfigFieldChoiceAttributes(val *IncidentConfigFieldChoiceAttributes) *NullableIncidentConfigFieldChoiceAttributes {
	return &NullableIncidentConfigFieldChoiceAttributes{value: val, isSet: true}
}

func (v NullableIncidentConfigFieldChoiceAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentConfigFieldChoiceAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
