/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// IncidentConfigField Represents an Incident Config Field Item.
type IncidentConfigField struct {
	Attributes *IncidentConfigFieldAttributes `json:"attributes,omitempty"`
	// Unique identifier that represents the Incident Config Field.
	Id            *string                           `json:"id,omitempty"`
	Relationships *IncidentConfigFieldRelationships `json:"relationships,omitempty"`
	// JSONAPI Model Type
	Type *string `json:"type,omitempty"`
}

// NewIncidentConfigField instantiates a new IncidentConfigField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentConfigField() *IncidentConfigField {
	this := IncidentConfigField{}
	return &this
}

// NewIncidentConfigFieldWithDefaults instantiates a new IncidentConfigField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentConfigFieldWithDefaults() *IncidentConfigField {
	this := IncidentConfigField{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *IncidentConfigField) GetAttributes() IncidentConfigFieldAttributes {
	if o == nil || o.Attributes == nil {
		var ret IncidentConfigFieldAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigField) GetAttributesOk() (*IncidentConfigFieldAttributes, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *IncidentConfigField) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given IncidentConfigFieldAttributes and assigns it to the Attributes field.
func (o *IncidentConfigField) SetAttributes(v IncidentConfigFieldAttributes) {
	o.Attributes = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IncidentConfigField) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigField) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IncidentConfigField) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *IncidentConfigField) SetId(v string) {
	o.Id = &v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *IncidentConfigField) GetRelationships() IncidentConfigFieldRelationships {
	if o == nil || o.Relationships == nil {
		var ret IncidentConfigFieldRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigField) GetRelationshipsOk() (*IncidentConfigFieldRelationships, bool) {
	if o == nil || o.Relationships == nil {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *IncidentConfigField) HasRelationships() bool {
	if o != nil && o.Relationships != nil {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given IncidentConfigFieldRelationships and assigns it to the Relationships field.
func (o *IncidentConfigField) SetRelationships(v IncidentConfigFieldRelationships) {
	o.Relationships = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IncidentConfigField) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigField) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IncidentConfigField) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *IncidentConfigField) SetType(v string) {
	o.Type = &v
}

func (o IncidentConfigField) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Relationships != nil {
		toSerialize["relationships"] = o.Relationships
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableIncidentConfigField struct {
	value *IncidentConfigField
	isSet bool
}

func (v NullableIncidentConfigField) Get() *IncidentConfigField {
	return v.value
}

func (v *NullableIncidentConfigField) Set(val *IncidentConfigField) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentConfigField) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentConfigField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentConfigField(val *IncidentConfigField) *NullableIncidentConfigField {
	return &NullableIncidentConfigField{value: val, isSet: true}
}

func (v NullableIncidentConfigField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentConfigField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
