/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// ServicePayload Represents the JSON API Payload of a Service Item.
type ServicePayload struct {
	Data Service `json:"data"`
	// Service payloads.
	Included *[]UserJSONAPIResponse `json:"included,omitempty"`
}

// NewServicePayload instantiates a new ServicePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicePayload(data Service) *ServicePayload {
	this := ServicePayload{}
	this.Data = data
	return &this
}

// NewServicePayloadWithDefaults instantiates a new ServicePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicePayloadWithDefaults() *ServicePayload {
	this := ServicePayload{}
	return &this
}

// GetData returns the Data field value
func (o *ServicePayload) GetData() Service {
	if o == nil {
		var ret Service
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ServicePayload) GetDataOk() (*Service, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ServicePayload) SetData(v Service) {
	o.Data = v
}

// GetIncluded returns the Included field value if set, zero value otherwise.
func (o *ServicePayload) GetIncluded() []UserJSONAPIResponse {
	if o == nil || o.Included == nil {
		var ret []UserJSONAPIResponse
		return ret
	}
	return *o.Included
}

// GetIncludedOk returns a tuple with the Included field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicePayload) GetIncludedOk() (*[]UserJSONAPIResponse, bool) {
	if o == nil || o.Included == nil {
		return nil, false
	}
	return o.Included, true
}

// HasIncluded returns a boolean if a field has been set.
func (o *ServicePayload) HasIncluded() bool {
	if o != nil && o.Included != nil {
		return true
	}

	return false
}

// SetIncluded gets a reference to the given []UserJSONAPIResponse and assigns it to the Included field.
func (o *ServicePayload) SetIncluded(v []UserJSONAPIResponse) {
	o.Included = &v
}

func (o ServicePayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if o.Included != nil {
		toSerialize["included"] = o.Included
	}
	return json.Marshal(toSerialize)
}

type NullableServicePayload struct {
	value *ServicePayload
	isSet bool
}

func (v NullableServicePayload) Get() *ServicePayload {
	return v.value
}

func (v *NullableServicePayload) Set(val *ServicePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableServicePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableServicePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicePayload(val *ServicePayload) *NullableServicePayload {
	return &NullableServicePayload{value: val, isSet: true}
}

func (v NullableServicePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
