/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
	"fmt"
)

// IncidentFacetTermsAggregationDataSchemaCountOneOf struct for IncidentFacetTermsAggregationDataSchemaCountOneOf
type IncidentFacetTermsAggregationDataSchemaCountOneOf struct {
	IncidentFacetTermsAggregationDataSchemaCountOneOfInterface interface{}
}

func (s IncidentFacetTermsAggregationDataSchemaCountOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.IncidentFacetTermsAggregationDataSchemaCountOneOfInterface)
}

func (s *IncidentFacetTermsAggregationDataSchemaCountOneOf) UnmarshalJSON(src []byte) error {
	var err error
	return fmt.Errorf("No oneOf model could be deserialized from payload: %s", string(src))
}

type NullableIncidentFacetTermsAggregationDataSchemaCountOneOf struct {
	value *IncidentFacetTermsAggregationDataSchemaCountOneOf
	isSet bool
}

func (v NullableIncidentFacetTermsAggregationDataSchemaCountOneOf) Get() *IncidentFacetTermsAggregationDataSchemaCountOneOf {
	return v.value
}

func (v *NullableIncidentFacetTermsAggregationDataSchemaCountOneOf) Set(val *IncidentFacetTermsAggregationDataSchemaCountOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentFacetTermsAggregationDataSchemaCountOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentFacetTermsAggregationDataSchemaCountOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentFacetTermsAggregationDataSchemaCountOneOf(val *IncidentFacetTermsAggregationDataSchemaCountOneOf) *NullableIncidentFacetTermsAggregationDataSchemaCountOneOf {
	return &NullableIncidentFacetTermsAggregationDataSchemaCountOneOf{value: val, isSet: true}
}

func (v NullableIncidentFacetTermsAggregationDataSchemaCountOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentFacetTermsAggregationDataSchemaCountOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
