/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// IncidentFacetSchema The common Facet schema interface payload.
type IncidentFacetSchema struct {
	// A facet definition.
	Data *IncidentFacetSchemaDataOneOf `json:"data,omitempty"`
	Type *IncidentFacetType            `json:"type,omitempty"`
}

// NewIncidentFacetSchema instantiates a new IncidentFacetSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentFacetSchema() *IncidentFacetSchema {
	this := IncidentFacetSchema{}
	return &this
}

// NewIncidentFacetSchemaWithDefaults instantiates a new IncidentFacetSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentFacetSchemaWithDefaults() *IncidentFacetSchema {
	this := IncidentFacetSchema{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *IncidentFacetSchema) GetData() IncidentFacetSchemaDataOneOf {
	if o == nil || o.Data == nil {
		var ret IncidentFacetSchemaDataOneOf
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentFacetSchema) GetDataOk() (*IncidentFacetSchemaDataOneOf, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *IncidentFacetSchema) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given IncidentFacetSchemaDataOneOf and assigns it to the Data field.
func (o *IncidentFacetSchema) SetData(v IncidentFacetSchemaDataOneOf) {
	o.Data = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IncidentFacetSchema) GetType() IncidentFacetType {
	if o == nil || o.Type == nil {
		var ret IncidentFacetType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentFacetSchema) GetTypeOk() (*IncidentFacetType, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IncidentFacetSchema) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given IncidentFacetType and assigns it to the Type field.
func (o *IncidentFacetSchema) SetType(v IncidentFacetType) {
	o.Type = &v
}

func (o IncidentFacetSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableIncidentFacetSchema struct {
	value *IncidentFacetSchema
	isSet bool
}

func (v NullableIncidentFacetSchema) Get() *IncidentFacetSchema {
	return v.value
}

func (v *NullableIncidentFacetSchema) Set(val *IncidentFacetSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentFacetSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentFacetSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentFacetSchema(val *IncidentFacetSchema) *NullableIncidentFacetSchema {
	return &NullableIncidentFacetSchema{value: val, isSet: true}
}

func (v NullableIncidentFacetSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentFacetSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
