/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// IncidentTodoListPayload Represents the JSON API Payload of a List of Incident Todo Items.
type IncidentTodoListPayload struct {
	// The Incident Todos.
	Data []IncidentTodo `json:"data"`
	// The User relationships.
	Included *[]UserJSONAPIResponse `json:"included,omitempty"`
	Meta     *QueryMetadata         `json:"meta,omitempty"`
}

// NewIncidentTodoListPayload instantiates a new IncidentTodoListPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentTodoListPayload(data []IncidentTodo) *IncidentTodoListPayload {
	this := IncidentTodoListPayload{}
	this.Data = data
	return &this
}

// NewIncidentTodoListPayloadWithDefaults instantiates a new IncidentTodoListPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentTodoListPayloadWithDefaults() *IncidentTodoListPayload {
	this := IncidentTodoListPayload{}
	return &this
}

// GetData returns the Data field value
func (o *IncidentTodoListPayload) GetData() []IncidentTodo {
	if o == nil {
		var ret []IncidentTodo
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *IncidentTodoListPayload) GetDataOk() (*[]IncidentTodo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *IncidentTodoListPayload) SetData(v []IncidentTodo) {
	o.Data = v
}

// GetIncluded returns the Included field value if set, zero value otherwise.
func (o *IncidentTodoListPayload) GetIncluded() []UserJSONAPIResponse {
	if o == nil || o.Included == nil {
		var ret []UserJSONAPIResponse
		return ret
	}
	return *o.Included
}

// GetIncludedOk returns a tuple with the Included field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentTodoListPayload) GetIncludedOk() (*[]UserJSONAPIResponse, bool) {
	if o == nil || o.Included == nil {
		return nil, false
	}
	return o.Included, true
}

// HasIncluded returns a boolean if a field has been set.
func (o *IncidentTodoListPayload) HasIncluded() bool {
	if o != nil && o.Included != nil {
		return true
	}

	return false
}

// SetIncluded gets a reference to the given []UserJSONAPIResponse and assigns it to the Included field.
func (o *IncidentTodoListPayload) SetIncluded(v []UserJSONAPIResponse) {
	o.Included = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *IncidentTodoListPayload) GetMeta() QueryMetadata {
	if o == nil || o.Meta == nil {
		var ret QueryMetadata
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentTodoListPayload) GetMetaOk() (*QueryMetadata, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *IncidentTodoListPayload) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given QueryMetadata and assigns it to the Meta field.
func (o *IncidentTodoListPayload) SetMeta(v QueryMetadata) {
	o.Meta = &v
}

func (o IncidentTodoListPayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if o.Included != nil {
		toSerialize["included"] = o.Included
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableIncidentTodoListPayload struct {
	value *IncidentTodoListPayload
	isSet bool
}

func (v NullableIncidentTodoListPayload) Get() *IncidentTodoListPayload {
	return v.value
}

func (v *NullableIncidentTodoListPayload) Set(val *IncidentTodoListPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentTodoListPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentTodoListPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentTodoListPayload(val *IncidentTodoListPayload) *NullableIncidentTodoListPayload {
	return &NullableIncidentTodoListPayload{value: val, isSet: true}
}

func (v NullableIncidentTodoListPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentTodoListPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
