/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// IncidentSelectionRelationshipsField The Incident Config Field relationship.
type IncidentSelectionRelationshipsField struct {
	Data *IncidentConfigField `json:"data,omitempty"`
}

// NewIncidentSelectionRelationshipsField instantiates a new IncidentSelectionRelationshipsField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentSelectionRelationshipsField() *IncidentSelectionRelationshipsField {
	this := IncidentSelectionRelationshipsField{}
	return &this
}

// NewIncidentSelectionRelationshipsFieldWithDefaults instantiates a new IncidentSelectionRelationshipsField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentSelectionRelationshipsFieldWithDefaults() *IncidentSelectionRelationshipsField {
	this := IncidentSelectionRelationshipsField{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *IncidentSelectionRelationshipsField) GetData() IncidentConfigField {
	if o == nil || o.Data == nil {
		var ret IncidentConfigField
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentSelectionRelationshipsField) GetDataOk() (*IncidentConfigField, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *IncidentSelectionRelationshipsField) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given IncidentConfigField and assigns it to the Data field.
func (o *IncidentSelectionRelationshipsField) SetData(v IncidentConfigField) {
	o.Data = &v
}

func (o IncidentSelectionRelationshipsField) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableIncidentSelectionRelationshipsField struct {
	value *IncidentSelectionRelationshipsField
	isSet bool
}

func (v NullableIncidentSelectionRelationshipsField) Get() *IncidentSelectionRelationshipsField {
	return v.value
}

func (v *NullableIncidentSelectionRelationshipsField) Set(val *IncidentSelectionRelationshipsField) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentSelectionRelationshipsField) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentSelectionRelationshipsField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentSelectionRelationshipsField(val *IncidentSelectionRelationshipsField) *NullableIncidentSelectionRelationshipsField {
	return &NullableIncidentSelectionRelationshipsField{value: val, isSet: true}
}

func (v NullableIncidentSelectionRelationshipsField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentSelectionRelationshipsField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
