/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// IncidentSelectionPayload Represents the JSON API Payload of an Incident Selection Item.
type IncidentSelectionPayload struct {
	Data IncidentSelection `json:"data"`
	// The User relationships.
	Included *[]UserJSONAPIResponse `json:"included,omitempty"`
}

// NewIncidentSelectionPayload instantiates a new IncidentSelectionPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentSelectionPayload(data IncidentSelection) *IncidentSelectionPayload {
	this := IncidentSelectionPayload{}
	this.Data = data
	return &this
}

// NewIncidentSelectionPayloadWithDefaults instantiates a new IncidentSelectionPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentSelectionPayloadWithDefaults() *IncidentSelectionPayload {
	this := IncidentSelectionPayload{}
	return &this
}

// GetData returns the Data field value
func (o *IncidentSelectionPayload) GetData() IncidentSelection {
	if o == nil {
		var ret IncidentSelection
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *IncidentSelectionPayload) GetDataOk() (*IncidentSelection, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *IncidentSelectionPayload) SetData(v IncidentSelection) {
	o.Data = v
}

// GetIncluded returns the Included field value if set, zero value otherwise.
func (o *IncidentSelectionPayload) GetIncluded() []UserJSONAPIResponse {
	if o == nil || o.Included == nil {
		var ret []UserJSONAPIResponse
		return ret
	}
	return *o.Included
}

// GetIncludedOk returns a tuple with the Included field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentSelectionPayload) GetIncludedOk() (*[]UserJSONAPIResponse, bool) {
	if o == nil || o.Included == nil {
		return nil, false
	}
	return o.Included, true
}

// HasIncluded returns a boolean if a field has been set.
func (o *IncidentSelectionPayload) HasIncluded() bool {
	if o != nil && o.Included != nil {
		return true
	}

	return false
}

// SetIncluded gets a reference to the given []UserJSONAPIResponse and assigns it to the Included field.
func (o *IncidentSelectionPayload) SetIncluded(v []UserJSONAPIResponse) {
	o.Included = &v
}

func (o IncidentSelectionPayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if o.Included != nil {
		toSerialize["included"] = o.Included
	}
	return json.Marshal(toSerialize)
}

type NullableIncidentSelectionPayload struct {
	value *IncidentSelectionPayload
	isSet bool
}

func (v NullableIncidentSelectionPayload) Get() *IncidentSelectionPayload {
	return v.value
}

func (v *NullableIncidentSelectionPayload) Set(val *IncidentSelectionPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentSelectionPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentSelectionPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentSelectionPayload(val *IncidentSelectionPayload) *NullableIncidentSelectionPayload {
	return &NullableIncidentSelectionPayload{value: val, isSet: true}
}

func (v NullableIncidentSelectionPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentSelectionPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
