/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// IncidentConfigFieldType ID representing the type of field, such as dropdown or multiselect
type IncidentConfigFieldType int32

// List of IncidentConfigFieldType
const (
	INCIDENTCONFIGFIELDTYPE_DROPDOWN    IncidentConfigFieldType = 1
	INCIDENTCONFIGFIELDTYPE_MULTISELECT IncidentConfigFieldType = 2
)

// Ptr returns reference to IncidentConfigFieldType value
func (v IncidentConfigFieldType) Ptr() *IncidentConfigFieldType {
	return &v
}

type NullableIncidentConfigFieldType struct {
	value *IncidentConfigFieldType
	isSet bool
}

func (v NullableIncidentConfigFieldType) Get() *IncidentConfigFieldType {
	return v.value
}

func (v *NullableIncidentConfigFieldType) Set(val *IncidentConfigFieldType) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentConfigFieldType) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentConfigFieldType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentConfigFieldType(val *IncidentConfigFieldType) *NullableIncidentConfigFieldType {
	return &NullableIncidentConfigFieldType{value: val, isSet: true}
}

func (v NullableIncidentConfigFieldType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentConfigFieldType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
