/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// IncidentSearchAttributes The Incident Search attributes.
type IncidentSearchAttributes struct {
	// A mapping of search facets by facet name.
	Facets map[string]IncidentFacetSchema `json:"facets,omitempty"`
	// The matched incidents if any.
	Incidents *[]IncidentPayload `json:"incidents,omitempty"`
	// The total count of matched incidents.
	Total *int64 `json:"total,omitempty"`
}

// NewIncidentSearchAttributes instantiates a new IncidentSearchAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentSearchAttributes() *IncidentSearchAttributes {
	this := IncidentSearchAttributes{}
	return &this
}

// NewIncidentSearchAttributesWithDefaults instantiates a new IncidentSearchAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentSearchAttributesWithDefaults() *IncidentSearchAttributes {
	this := IncidentSearchAttributes{}
	return &this
}

// GetFacets returns the Facets field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IncidentSearchAttributes) GetFacets() map[string]IncidentFacetSchema {
	if o == nil {
		var ret map[string]IncidentFacetSchema
		return ret
	}
	return o.Facets
}

// GetFacetsOk returns a tuple with the Facets field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IncidentSearchAttributes) GetFacetsOk() (*map[string]IncidentFacetSchema, bool) {
	if o == nil || o.Facets == nil {
		return nil, false
	}
	return &o.Facets, true
}

// HasFacets returns a boolean if a field has been set.
func (o *IncidentSearchAttributes) HasFacets() bool {
	if o != nil && o.Facets != nil {
		return true
	}

	return false
}

// SetFacets gets a reference to the given map[string]IncidentFacetSchema and assigns it to the Facets field.
func (o *IncidentSearchAttributes) SetFacets(v map[string]IncidentFacetSchema) {
	o.Facets = v
}

// GetIncidents returns the Incidents field value if set, zero value otherwise.
func (o *IncidentSearchAttributes) GetIncidents() []IncidentPayload {
	if o == nil || o.Incidents == nil {
		var ret []IncidentPayload
		return ret
	}
	return *o.Incidents
}

// GetIncidentsOk returns a tuple with the Incidents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentSearchAttributes) GetIncidentsOk() (*[]IncidentPayload, bool) {
	if o == nil || o.Incidents == nil {
		return nil, false
	}
	return o.Incidents, true
}

// HasIncidents returns a boolean if a field has been set.
func (o *IncidentSearchAttributes) HasIncidents() bool {
	if o != nil && o.Incidents != nil {
		return true
	}

	return false
}

// SetIncidents gets a reference to the given []IncidentPayload and assigns it to the Incidents field.
func (o *IncidentSearchAttributes) SetIncidents(v []IncidentPayload) {
	o.Incidents = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *IncidentSearchAttributes) GetTotal() int64 {
	if o == nil || o.Total == nil {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentSearchAttributes) GetTotalOk() (*int64, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *IncidentSearchAttributes) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *IncidentSearchAttributes) SetTotal(v int64) {
	o.Total = &v
}

func (o IncidentSearchAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Facets != nil {
		toSerialize["facets"] = o.Facets
	}
	if o.Incidents != nil {
		toSerialize["incidents"] = o.Incidents
	}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullableIncidentSearchAttributes struct {
	value *IncidentSearchAttributes
	isSet bool
}

func (v NullableIncidentSearchAttributes) Get() *IncidentSearchAttributes {
	return v.value
}

func (v *NullableIncidentSearchAttributes) Set(val *IncidentSearchAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentSearchAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentSearchAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentSearchAttributes(val *IncidentSearchAttributes) *NullableIncidentSearchAttributes {
	return &NullableIncidentSearchAttributes{value: val, isSet: true}
}

func (v NullableIncidentSearchAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentSearchAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
