/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// IncidentConfigFieldChoiceListPayload Represents the JSON API Payload of a List of Incident Config Field Choice Items.
type IncidentConfigFieldChoiceListPayload struct {
	// The Incident config field choices.
	Data []IncidentConfigFieldChoice `json:"data"`
	// The User relationships.
	Included *[]UserJSONAPIResponse `json:"included,omitempty"`
	Meta     *QueryMetadata         `json:"meta,omitempty"`
}

// NewIncidentConfigFieldChoiceListPayload instantiates a new IncidentConfigFieldChoiceListPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentConfigFieldChoiceListPayload(data []IncidentConfigFieldChoice) *IncidentConfigFieldChoiceListPayload {
	this := IncidentConfigFieldChoiceListPayload{}
	this.Data = data
	return &this
}

// NewIncidentConfigFieldChoiceListPayloadWithDefaults instantiates a new IncidentConfigFieldChoiceListPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentConfigFieldChoiceListPayloadWithDefaults() *IncidentConfigFieldChoiceListPayload {
	this := IncidentConfigFieldChoiceListPayload{}
	return &this
}

// GetData returns the Data field value
func (o *IncidentConfigFieldChoiceListPayload) GetData() []IncidentConfigFieldChoice {
	if o == nil {
		var ret []IncidentConfigFieldChoice
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *IncidentConfigFieldChoiceListPayload) GetDataOk() (*[]IncidentConfigFieldChoice, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *IncidentConfigFieldChoiceListPayload) SetData(v []IncidentConfigFieldChoice) {
	o.Data = v
}

// GetIncluded returns the Included field value if set, zero value otherwise.
func (o *IncidentConfigFieldChoiceListPayload) GetIncluded() []UserJSONAPIResponse {
	if o == nil || o.Included == nil {
		var ret []UserJSONAPIResponse
		return ret
	}
	return *o.Included
}

// GetIncludedOk returns a tuple with the Included field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigFieldChoiceListPayload) GetIncludedOk() (*[]UserJSONAPIResponse, bool) {
	if o == nil || o.Included == nil {
		return nil, false
	}
	return o.Included, true
}

// HasIncluded returns a boolean if a field has been set.
func (o *IncidentConfigFieldChoiceListPayload) HasIncluded() bool {
	if o != nil && o.Included != nil {
		return true
	}

	return false
}

// SetIncluded gets a reference to the given []UserJSONAPIResponse and assigns it to the Included field.
func (o *IncidentConfigFieldChoiceListPayload) SetIncluded(v []UserJSONAPIResponse) {
	o.Included = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *IncidentConfigFieldChoiceListPayload) GetMeta() QueryMetadata {
	if o == nil || o.Meta == nil {
		var ret QueryMetadata
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentConfigFieldChoiceListPayload) GetMetaOk() (*QueryMetadata, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *IncidentConfigFieldChoiceListPayload) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given QueryMetadata and assigns it to the Meta field.
func (o *IncidentConfigFieldChoiceListPayload) SetMeta(v QueryMetadata) {
	o.Meta = &v
}

func (o IncidentConfigFieldChoiceListPayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if o.Included != nil {
		toSerialize["included"] = o.Included
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableIncidentConfigFieldChoiceListPayload struct {
	value *IncidentConfigFieldChoiceListPayload
	isSet bool
}

func (v NullableIncidentConfigFieldChoiceListPayload) Get() *IncidentConfigFieldChoiceListPayload {
	return v.value
}

func (v *NullableIncidentConfigFieldChoiceListPayload) Set(val *IncidentConfigFieldChoiceListPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentConfigFieldChoiceListPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentConfigFieldChoiceListPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentConfigFieldChoiceListPayload(val *IncidentConfigFieldChoiceListPayload) *NullableIncidentConfigFieldChoiceListPayload {
	return &NullableIncidentConfigFieldChoiceListPayload{value: val, isSet: true}
}

func (v NullableIncidentConfigFieldChoiceListPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentConfigFieldChoiceListPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
