/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// IncidentPostmortem Represents an Incident Postmortem Item.
type IncidentPostmortem struct {
	Attributes *IncidentPostmortemAttributes `json:"attributes,omitempty"`
	// The Postmortem ID.
	Id            *string                           `json:"id,omitempty"`
	Relationships *IncidentConfigFieldRelationships `json:"relationships,omitempty"`
	// JSONAPI Model Type
	Type *string `json:"type,omitempty"`
}

// NewIncidentPostmortem instantiates a new IncidentPostmortem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentPostmortem() *IncidentPostmortem {
	this := IncidentPostmortem{}
	return &this
}

// NewIncidentPostmortemWithDefaults instantiates a new IncidentPostmortem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentPostmortemWithDefaults() *IncidentPostmortem {
	this := IncidentPostmortem{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *IncidentPostmortem) GetAttributes() IncidentPostmortemAttributes {
	if o == nil || o.Attributes == nil {
		var ret IncidentPostmortemAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentPostmortem) GetAttributesOk() (*IncidentPostmortemAttributes, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *IncidentPostmortem) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given IncidentPostmortemAttributes and assigns it to the Attributes field.
func (o *IncidentPostmortem) SetAttributes(v IncidentPostmortemAttributes) {
	o.Attributes = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IncidentPostmortem) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentPostmortem) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IncidentPostmortem) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *IncidentPostmortem) SetId(v string) {
	o.Id = &v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *IncidentPostmortem) GetRelationships() IncidentConfigFieldRelationships {
	if o == nil || o.Relationships == nil {
		var ret IncidentConfigFieldRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentPostmortem) GetRelationshipsOk() (*IncidentConfigFieldRelationships, bool) {
	if o == nil || o.Relationships == nil {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *IncidentPostmortem) HasRelationships() bool {
	if o != nil && o.Relationships != nil {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given IncidentConfigFieldRelationships and assigns it to the Relationships field.
func (o *IncidentPostmortem) SetRelationships(v IncidentConfigFieldRelationships) {
	o.Relationships = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IncidentPostmortem) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentPostmortem) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IncidentPostmortem) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *IncidentPostmortem) SetType(v string) {
	o.Type = &v
}

func (o IncidentPostmortem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Relationships != nil {
		toSerialize["relationships"] = o.Relationships
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableIncidentPostmortem struct {
	value *IncidentPostmortem
	isSet bool
}

func (v NullableIncidentPostmortem) Get() *IncidentPostmortem {
	return v.value
}

func (v *NullableIncidentPostmortem) Set(val *IncidentPostmortem) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentPostmortem) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentPostmortem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentPostmortem(val *IncidentPostmortem) *NullableIncidentPostmortem {
	return &NullableIncidentPostmortem{value: val, isSet: true}
}

func (v NullableIncidentPostmortem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentPostmortem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
