/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadog

import (
	"encoding/json"
)

// IncidentSearchPayload Represents the JSON API Payload of a List of Incident Items.
type IncidentSearchPayload struct {
	Data IncidentSearch `json:"data"`
	Meta *QueryMetadata `json:"meta,omitempty"`
}

// NewIncidentSearchPayload instantiates a new IncidentSearchPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncidentSearchPayload(data IncidentSearch) *IncidentSearchPayload {
	this := IncidentSearchPayload{}
	this.Data = data
	return &this
}

// NewIncidentSearchPayloadWithDefaults instantiates a new IncidentSearchPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncidentSearchPayloadWithDefaults() *IncidentSearchPayload {
	this := IncidentSearchPayload{}
	return &this
}

// GetData returns the Data field value
func (o *IncidentSearchPayload) GetData() IncidentSearch {
	if o == nil {
		var ret IncidentSearch
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *IncidentSearchPayload) GetDataOk() (*IncidentSearch, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *IncidentSearchPayload) SetData(v IncidentSearch) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *IncidentSearchPayload) GetMeta() QueryMetadata {
	if o == nil || o.Meta == nil {
		var ret QueryMetadata
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncidentSearchPayload) GetMetaOk() (*QueryMetadata, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *IncidentSearchPayload) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given QueryMetadata and assigns it to the Meta field.
func (o *IncidentSearchPayload) SetMeta(v QueryMetadata) {
	o.Meta = &v
}

func (o IncidentSearchPayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableIncidentSearchPayload struct {
	value *IncidentSearchPayload
	isSet bool
}

func (v NullableIncidentSearchPayload) Get() *IncidentSearchPayload {
	return v.value
}

func (v *NullableIncidentSearchPayload) Set(val *IncidentSearchPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableIncidentSearchPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableIncidentSearchPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncidentSearchPayload(val *IncidentSearchPayload) *NullableIncidentSearchPayload {
	return &NullableIncidentSearchPayload{value: val, isSet: true}
}

func (v NullableIncidentSearchPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncidentSearchPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
